Document: twemproxy
Title: Debian twemproxy Manual
Author: <insert document author here>
Abstract: This manual describes what twemproxy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/twemproxy/twemproxy.sgml.gz

Format: postscript
Files: /usr/share/doc/twemproxy/twemproxy.ps.gz

Format: text
Files: /usr/share/doc/twemproxy/twemproxy.text.gz

Format: HTML
Index: /usr/share/doc/twemproxy/html/index.html
Files: /usr/share/doc/twemproxy/html/*.html
